### ISSUE TITLE
Feature request: multiple levels entrypoints

### ISSUE THREAD

**Issue by duduklein** [vintasoftware/tapioca-wrapper#122]
I would be nice to have "multiple levels" entrypoints. For example, looking at disqus wrapper' [resource_mapping](https://github.com/marctc/tapioca-disqus/tree/master/tapioca_disqus/resource_mapping), we see that we have many files and they actually correspond to prefixes in the urls. 

The way tapioca is today forces us to repeat the prefix in the resource_mapping dict and in the resource url. 

Instead of accessing the entrypoints as `api.blacklists_add` and `api.blacklists_remove`, we would access it as `api.blacklists.add` and `api.blacklists.remove`.

[Tortilla](https://github.com/redodo/tortilla) does this, but that repo does not seems to support oauth2 and does not seem to be really active / maintained.

If you think it's a good idea, I may be able to take a look at the Tortilla to see if it's easy to adapt tapioca's code.

Thanks

**Comment by filipeximenes** [comment]
Hi @duduklein, so you are proposing we can organize the resource_mapping like this right?
```
'thread': {    
    'resource': 'threads',
    'subresources': {
        'close': {
            'resource': 'threads/close.json',
            'docs': 'https://disqus.com/api/docs/threads/close/',
            'methods': ['POST'],
        },
        'create': {
            'resource': 'threads/create.json',
            'docs': 'https://disqus.com/api/docs/threads/create/',
            'methods': ['POST'],
        },
        'details': {
            'resource': 'threads/details.json',
            'docs': 'https://disqus.com/api/docs/threads/details/',
            'methods': ['GET'],
        },
    }
}
```
At first glance the way tortilla does to this looks interesting and natural. But it comes with some problems:

1. In the example above, as much as there are many resources with a url of the type 'threads/{something}.json', it's possible an API where there isn't an endpoint 'threads/', so doing `api.threads.get()` will actually lead the user to try to fetch an invalid endpoint. This is a bit misleading.
2. Tapioca is made to be build for Disqus once and used multiple times by developers as opposed to Tortilla where every time you want to integrate with Disqus you need to refer to the documentation and manually "concatenate" strings to form a url resource. Although this is a valid approach, Tapioca is made to feel like you are using a "conventional" API client rather than building endpoint urls. 
3. Since developers will only be specifying resource urls once, it's not that much of a work to write down all urls in it's complete form. Modifying this would add complexity to the process with very low gain in my opinion.

**Comment by filipeximenes** [comment]
Closing this for now. LMK if you have any other ideas to discuss :)

**Comment by jeanmask** [comment]
My suggestion is support something like the google api discovery, by example:

https://iam.googleapis.com/$discovery/rest?version=v1

It's a mix of json schema and your proposed archtecture @filipeximenes.
