### ISSUE TITLE
Refresh token support 

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#13]
We can think  in a way to allow automatic refresh of access token for services that implement refresh tokens

**Comment by era** [comment]
Just adding one example of API that requires that: https://developer.paypal.com/webapps/developer/docs/api/#authentication--headers

**Comment by era** [comment]
What if we use the same pattern as https://github.com/vintasoftware/tapioca-wrapper/issues/49? We create a simple support to it and the user can override it just by creating a object with a is_valid and refresh_token methods or something like that. What do you think?

**Comment by filipeximenes** [comment]
I think this is not the same situation. Each service implements it's own way of refreshing tokens, but once implemented, there's no reason way would someone change it. Here is how this normally goes:

1a. You now (probably by storing the time it was acquired or the time it will expire) that you have a expired token.
1b. You make a request and the service returns an error code informing you have a expired token
2. You perform a call to the service with a "refresh_token" "grant_type", the token and the desired scope (the scope cannot request for more access than the original access_token call). The implementation of this step will vary according to each service, but the logic is normally the same.
3. The service will return a new access_token that you can use to perform calls.
4. You perform the call originally intended using the new access_token.

Some of the things that should be taken in account for this feature are:
- The client should be able to opt to or not to automatically perform the token refreshing operation in case of a request failure. (maybe a parameter passed during initialization)
- The operation should happen in the adapter, so each service can implement it's own process.

**Comment by era** [comment]
@filipeximenes I think we are saying the same thing :), but with a small difference. I think that we could implement by default some auth protocols and let the user choose if he needs to create one new or just change something in the default implementation. I'm saying this because I (guess) most of the APIs implement Oauth2 or Basic Auth.

But If you think that this is not the way tapioca was made to be and should be more generic possible, I understand :).

**Comment by filipeximenes** [comment]
Cool, can you send some code snippets showing what you have in mind? Don't bother with details, just show how you think this should work.

**Comment by era** [comment]
@filipeximenes Basic something like: https://gist.github.com/era/83ab049a88552f4b0a79

I do something like this in a paypal library, because the token needs to be refresh every 8 hours. I think Oauth2 has a similar behaviour, right? You just have to hit an endpoint with same data to get the new token. If the user is using something different she/he can create a class that has the same methods of BasicAuth.

What do you think? Will this help the user's life?

**Comment by filipeximenes** [comment]
So here is my ideia, and it kind of uses the same approach as #86.

We can have a ```refresh_token``` method that is empty by default (probably raises and exception), and can be freely customized by clients. We can provide mixins that implement the protocols that have some default way of working. Then, we can have a method that analyses a response and tells if the token needs refreshing (this can also be overridden by each service), lastly, there should be an optional parameter in all http request methods that allows user to explicitly say that a new token should be fetched in case the current one is not valid (eg.: ``refresh_auth=False``)

What do you think? Tell me if this is not clear, I can try to put this in pseudocode if it helps.

**Comment by era** [comment]
Perfect :), It was very clear. I'll work on it next week.
