### ISSUE TITLE
Support OrderedDict in the core

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/tapioca-wrapper#85]

**Comment by willplaehn** [comment]
I'll work on this

**Comment by willplaehn** [comment]
Seems that this is only an issue with Python 2. The pprint module was improved and handles OrderedDict (and other containers) well in Python 3.4 that I'm testing with.

Is this something that should be patched conditional on the version of Python the user is running?

Alternative is to add a usage note in the documentation for API mixins that return OrderedDict.

**Comment by filipeximenes** [comment]
Can you see any problems in case we did:
```
dict(self._data)
```

**Comment by filipeximenes** [comment]
dumping to json seems to be safer: http://stackoverflow.com/questions/4301069/any-way-to-properly-pretty-print-ordered-dictionaries-in-python

**Comment by willplaehn** [comment]
The json.dumps approach is better since it preserves order for display.

Disadvantage as noted in the stackoverflow thread is that we lose the type information -- it prints as a dictionary. Here's an [interesting thread](http://stackoverflow.com/questions/1131495/in-xml-is-order-important) about XML ordering (it sometimes matters).

We should consider these tradeoffs when using `json.dumps`:

- Ordering is implicit: it's not clear from the printed output that this is an ordered data structure
- Similarly, copy / paste from the terminal will lose ordering

`json.dumps` is more readable than using `OrderedDict.__repr__()`, and I think that issues from ordering ambiguity will be rare. However, it may be helpful to the user to have knowledge that the returned data type from Tapioca is ordered for their own programming purposes.

Is there a disadvantage to adding a warning like:
```
"Response data is of type OrderedDict, printing as dict:"
```
before printing an OrderedDict in this way?

**Comment by filipeximenes** [comment]
Very good points. 
About the ordering: since our purpose is to allow developers to explore the wrapper, I don't think is a problem to mix the ordering. 

I like the idea of printing a message alerting the user. Let's go with that for now and we change if we have a better idea in the future.
